### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by LoreleiAurora** [roots/grunt-wp-version#1]
How can i call multiple instances of this script? I have tried the following:

Example 1

``` js
version: {
      options: {
        file: 'content/mu-plugins/asset-manager/register-styles.php',
        css: 'content/assets/css/main.min.css',
        cssHandle: 'roots_main'
      },
      options: {
        file: 'content/mu-plugins/asset-manager/register-scripts.php',
        js: 'content/assets/js/scripts.min.js',
        jsHandle: 'roots_scripts'
      }
    },
```

Example 2

``` js
version: {
      options: {
        file: 'content/mu-plugins/asset-manager/register-styles.php',
        css: 'content/assets/css/main.min.css',
        cssHandle: 'roots_main',
        file: 'content/mu-plugins/asset-manager/register-scripts.php',
        js: 'content/assets/js/scripts.min.js',
        jsHandle: 'roots_scripts'
      }
    },
```

**Comment by hariadi** [comment]
`grunt version` is single task mean you can't run multiple. Also all `options` is mandatory.

**Comment by retlehs** [comment]
yeah, this was meant as a quick fix to get this task outside of the main roots repo. will need to move away from using this and instead use https://github.com/hariadi/grunt-wp-assets

**Comment by hariadi** [comment]
There couple of issue in https://github.com/hariadi/grunt-wp-assets
- different task name (maybe change to `version`).
-  not support querystring in filename revving `c5f6f584.main.min.css` instead of `main.min.css?c5f6f584b79463f58c223f18fef206ef`.

@retlehs Do you mind if I move [that repo](https://github.com/hariadi/grunt-wp-assets) to roots org, so many people can maintainer of it? But that's entirely up to you.

**Comment by retlehs** [comment]
i think getting those two issues fixed will make it perfect :+1: 

& if you'd like to move that repo over to the roots org that'd be awesome!

**Comment by hariadi** [comment]
As I do not have admin rights to roots, I transfer ownership. You can now change the rights and transfer to roots org.

**Comment by LoreleiAurora** [comment]
Thanks for the info, In the end I just wrote a new task to write a constant and referenced that on all register tasks.
see https://bitbucket.org/PropertyStork/asset-manager-node-module/src/5243b1adc442efe7210adc61c1739be02e908f64/tasks/version.js?at=master

**Comment by retlehs** [comment]
@hariadi thank you - all done, and added you to the repo
