### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ScottSmith95** [roots/grunt-wp-version#2]
A Readme.md file would be really helpful because this looks like a cool plugin, but I have no idea how to use it because there is no documentation.

**Comment by retlehs** [comment]
take a look at https://github.com/roots/grunt-wp-assets

this project is currently used by roots theme but will be replaced with the above project soon

**Comment by ScottSmith95** [comment]
OK, I see. I was browsing the roots theme and saw this plugin. Still, you may want to make a quick Readme that just says what you just told me.

**Comment by retlehs** [comment]
done
